### PR TITLE
Add -L / --dereference option

### PR DESCRIPTION
**Pull request by noamraph**
Hi,

I added an equivalent to `cp -L` = `cp --dereference` option. I need this for my work, where I want to replace a `cp` command on NFS which takes forever, and it's using `-L`. I tried to make it behave like `cp -L` does: just treat symlinks as if they were really the files or directories they refer to. FWIW, in my work I was able to replace the `cp -rL` with `cpz -L`, and it succeeded, reducing the copying time from 49 minutes to 4 minutes!

WDYT?

### CODE REVIEW

**Comment by noamraph** [comment]
@SUPERCILEX I now managed to make the tests pass on all platforms. What do you think about this feature/PR?

**Comment by SUPERCILEX** [comment]
> reducing the copying time from 49 minutes to 4 minutes

Holy shit! I'm very happy to see such a massive real world improvement, that's awesome.

Can you double check that my changes still work on your end? Then I'll merge.

**Comment by noamraph** [comment]
> > reducing the copying time from 49 minutes to 4 minutes
> 
> Holy shit! I'm very happy to see such a massive real world improvement, that's awesome.

Indeed! Thank you so much for the project!
> 
> Can you double check that my changes still work on your end? Then I'll merge.

I'm out of work now, I hope to test it on Sunday.

Also, your changes also tweak the code to my liking ;)

**Comment by SUPERCILEX** [comment]
> Also, your changes also tweak the code to my liking ;)

Yay! I'll be waiting for your confirmation. :+1:

**Comment by noamraph** [comment]
@SUPERCILEX I confirm, it still works with our CI!

**Comment by SUPERCILEX** [comment]
Sweet!

**Pull request merged**
